# -*- coding: utf-8 -*-
"""Gurgoan Sectors latlong.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S4bCBqJIxyDSzkiUaY6n9iEOUx8h4rf-
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/Gurgoan_Wrangled_Data_2.csv")

latlong=pd.read_csv("/latlong.csv")

latlong.head()

latlong['latitude'] = latlong['coordinates'].str.split(',').str.get(0).str.split('°').str.get(0).astype('float')
latlong['longitude'] = latlong['coordinates'].str.split(',').str.get(1).str.split('°').str.get(0).astype('float')

latlong.head()

latlong=latlong.drop('coordinates',axis=1)

latlong

latlong.shape

latlong.loc[130]=['badshahpur',77.0466318,28.3933996]

latlong.loc[130]

new_df=pd.merge(df,latlong,on='sector')

new_df.head()

new_df=new_df.drop('possession',axis=1)

group_df=new_df.groupby('sector').mean()[['price','area','price_per_sqft','longitude','latitude']]

group_df

import plotly.express as px
import plotly.graph_objects as go

fig = px.scatter_mapbox(group_df, lat="latitude", lon="longitude", color="price_per_sqft", size="area",
                        color_continuous_scale=px.colors.cyclical.IceFire, zoom=10,
                        mapbox_style="open-street-map", text=group_df.index)
fig.show()

from google.colab import files
group_df.to_csv("Gurgoan_Sectors_latlong.csv",index=False)
files.download("Gurgoan_Sectors_latlong.csv")

